// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://szrvkiolumfrgrqlpbsp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6cnZraW9sdW1mcmdycWxwYnNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI0NzYyNDksImV4cCI6MjA3ODA1MjI0OX0.5u9SiXNtN5cuTu8YW5yfUipEAH3kiVx0hEhMZRbUnpk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});